### ISSUE TITLE
[Feature request] initial support of INF file format

### ISSUE THREAD

**Issue by ohault** [dbohdan/initool#14]
C:\>initool version
0.14.1

C:\>initool get DOSNET.INF Version signature
Error: invalid line: "d1,disk1"

If all lines without a key=value are removed, there is no problem.

C:\>initool get DOSNET.INI Version signature
[Version]
signature="$Windows NT$"

I will be cool if initool could also support INF file forme with lines in sections with in the format of one or several tokens separated with a comma.

More information:
https://en.wikipedia.org/wiki/INF_file

**Comment by dbohdan** [comment]
Resolved through d7b72ad51300a5b5c4143b7c297570b5e770dba1.

**Comment by ohault** [comment]
Tested with version 0.15.0 with the new global option -p to disable the error (https://github.com/dbohdan/initool?tab=readme-ov-file#unparsable-lines)

 C:\>initool -p get DOSNET.INF Version signature
[Version]
signature="$Windows NT$"

There is no more error with this command, but this is not a support of the INI dialect used for INF files by Windows.

C:\Users\OHA\Desktop\INI\Test_initool>initool -p get DOSNET.INF [RootBootFiles]

no output meanwhile the content of a [RootBootFiles] section is 

[RootBootFiles]
d1,txtsetup.sif
d1,setupldr.bin,$LDR$
d1,ntdetect.com
d1,ntldr

**Comment by dbohdan** [comment]
You should not include the square brackets in the section argument. Try

    initool -p get DOSNET.INF RootBootFiles

**Comment by ohault** [comment]
I apology, I have been distracted.

Indeed, using the right syntax gives the expected result for a get on a section.

C:\>initool -p get DOSNET.INF RootBootFiles
[RootBootFiles]
d1,txtsetup.sif
d1,setupldr.bin,$LDR$
d1,ntdetect.com
d1,ntldr
