### ISSUE TITLE
[Feature request] initial support of REG file format

### ISSUE THREAD

**Issue by ohault** [dbohdan/initool#15]
https://docs.fileformat.com/executable/reg/

**Comment by dbohdan** [comment]
It would probably be useful to have some support for REG files and for INF files from #14. However, I don't want to implement subformats and dialects of INI. My goal with initool is to keep its scope and codebase small. Part of this is having one non-configurable parser that works with common INI constructs.

I think what I will do instead for now is add an option that passes through all lines initool doesn't recognize. This will allow you to work with files that aren't INI as initool understands it at your own risk.

**Comment by dbohdan** [comment]
Resolved through d7b72ad51300a5b5c4143b7c297570b5e770dba1.

**Comment by ohault** [comment]
To test support of REG file format, I have created some custom entries in a Windows Registry (Windows 10 x64) and exported then into [a REG file]([HCU-Test.reg.txt](https://github.com/dbohdan/initool/files/15370056/HCU-Test.reg.txt)) with [regedit.exe]

C:\>type HCU-Test.reg
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Test]
"binaire"=hex:00,01,00,10,10,10,10

[HKEY_CURRENT_USER\Test\subkey1]
"DWORD64"=hex(b):23,fe,53,00,00,00,00,00
"test_string"="blablabla"

[HKEY_CURRENT_USER\Test\subkey2]
"Multi"=hex(7):46,00,6f,00,6f,00,00,00,42,00,61,00,72,00,00,00,00,00

C:\>initool -p get HCU-Test.reg
 ■W i n d o w s   R e g i s t r y   E d i t o r   V e r s i o n   5 . 0 0

 [ H K E Y _ C U R R E N T _ U S E R \ T e s t ]
 " b i n " = h e x : 0 0 , 0 1 , 0 0 , 1 0 , 1 0 , 1 0 , 1 0

 [ H K E Y _ C U R R E N T _ U S E R \ T e s t \ s u b k e y 1 ]
 " D W O R D 6 4 " = h e x ( b ) : 2 3 , f e , 5 3 , 0 0 , 0 0 , 0 0 , 0 0 , 0 0
 " t e s t _ s t r i n g " = " b l a b l a b l a "

 [ H K E Y _ C U R R E N T _ U S E R \ T e s t \ s u b k e y 2 ]
 " M u l t i " = h e x ( 7 ) : 4 6 , 0 0 , 6 f , 0 0 , 6 f , 0 0 , 0 0 , 0 0 , 4 2 , 0 0 , 6 1 , 0 0 , 7 2 , 0 0 , 0 0 , 0 0 , 0 0 , 0 0

C:\>initool -p get HCU-Test.reg HKEY_CURRENT_USER\Test

C:\>echo %errorlevel%
1

In inicomp tool, an error message is displayed with an instruction for the user.
Error: File .................. is encoded as UTF16. Please convert it to ANSI or UTF8 first.

After, I opened HCU-Test.reg in Notepad.exe to save it back to from UTF-16 LE encoding to ANSI, UTF-8 and UTF-8 with BOM.

C:\>initool -p get HCU-Test_ANSI.reg HKEY_CURRENT_USER\Test\subkey1
[HKEY_CURRENT_USER\Test\subkey1]
"DWORD64"=hex(b):23,fe,53,00,00,00,00,00
"test_string"="blablabla"


C:\>initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1
[HKEY_CURRENT_USER\Test\subkey1]
"DWORD64"=hex(b):23,fe,53,00,00,00,00,00
"test_string"="blablabla"


C:\>initool -p get HCU-Test_UTF-8-withBOM.reg HKEY_CURRENT_USER\Test\subkey1
[HKEY_CURRENT_USER\Test\subkey1]
"DWORD64"=hex(b):23,fe,53,00,00,00,00,00
"test_string"="blablabla"

Lastly, I try to query a <key>

C:\>initool -p get HCU-Test_ANSI.reg HKEY_CURRENT_USER\Test\subkey1 test_string

C:\>initool -p get HCU-Test_ANSI.reg HKEY_CURRENT_USER\Test\subkey1 "test_string"

C:\>initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1 test_string

C:\>initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1 "test_string"

C:\>initool -p get HCU-Test_UTF-8-withBOM.reg HKEY_CURRENT_USER\Test\subkey1 test_string

C:\>initool -p get HCU-Test_UTF-8-withBOM.reg HKEY_CURRENT_USER\Test\subkey1 "test_string"

Summary
- no support of UTF-16 LE encoding
- no way to query a <key>

**Comment by dbohdan** [comment]
Command Prompt eats those quotation marks. You need to [pass the double quotes](https://stackoverflow.com/questions/7760545/escape-double-quotes-in-parameter) to initool. 

    initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1 """test_string"""

**Comment by ohault** [comment]
Thank you, indeed escaping the double-quotes provides the correct answer.

C:\>initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1 """test_string"""
[HKEY_CURRENT_USER\Test\subkey1]
"test_string"="blablabla"

But according to https://docs.fileformat.com/executable/reg/, for

[<Hive name>\<Key name>\<Subkey name>]
"Value name"=<Value type>:<Value data>

the command for a REG should look like this
C:\>initool -p get HCU-Test_UTF-8.reg HKEY_CURRENT_USER\Test\subkey1 test_string

This ticket can stay closed. I have renamed this ticket as initial support of REG file format, an INI dialect with its own details, meanwhile this initial REG file format support would require some specific documentation.

**Comment by dbohdan** [comment]
You're welcome. The command would look like what you say if initool supported the REG-file dialect of INI. It doesn't, so instead initool sees it as INI with double-quote characters in the key.
