### ISSUE TITLE
Does not accept # as a comment

### ISSUE THREAD

**Issue by chaoskcw** [dbohdan/initool#3]
The '#' sign is an alternative comment marker in most ini files. initool complains these are invalid lines. 

"Error: invalid line: ..."

Request supporting # as alternate comment marker.

**Comment by chaoskcw** [comment]
See https://en.wikipedia.org/wiki/INI_file

**Comment by dbohdan** [comment]
Thanks for a good suggestion! Implemented in [v0.8.0](https://github.com/dbohdan/initool/releases/tag/v0.8.0).
