### ISSUE TITLE
initool and php.ini enable extentsion syntax

### ISSUE THREAD

**Issue by spamhater-grav** [dbohdan/initool#6]
Hi there, trying to automate some php.ini changes

Want to enable an existing extension  which is disabled 
```;extension=bz2```
but I have tried to get a response via -g and trying to do a replacement with -s 
```initool -s php.ini PHP ;extension=bz2 extension=bz2```

but to know joy, is this possible or is it just bad syntax of initool by me
Many thanks 
initool - windows

**Comment by dbohdan** [comment]
Sorry, but initool cannot uncomment lines. I suggest using [sed](https://stackoverflow.com/a/71573266) or Awk instead. Sed for Windows is available through [busybox-w32](https://frippery.org/busybox/).
