### ISSUE TITLE
readlink: illegal option -- f

### ISSUE THREAD

**Issue by barracuda156** [dbohdan/initool#7]
Build fails on macOS on this:
```
make: Entering directory `/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_initool/initool/work/initool-75e6b71307ef65ad0061d761acc11713c2ee16f0'
mlton initool.mlb
sh test.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
make: *** [test] Error 1
```

**Comment by barracuda156** [comment]
Also this:
```
sh test.sh
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
make: *** [test] Error 1
```

**Comment by barracuda156** [comment]
Solution is either use `greadlink` and `gmktemp` from `coreutils`, or maybe this or alike: https://github.com/corda/corda-kubernetes-deployment/pull/9/files

**Comment by dbohdan** [comment]
I have modified `test.sh` to remove the GNUisms.  (GNU coreutils would be an  inconvenient dependency for macOS users.) I don't have a Mac to test it on. Please try again and tell me if it works.

**Comment by barracuda156** [comment]
@dbohdan Sorry for a delay. Yes, now it builds fine without depending on `coreutils`, which is awesome. (While `coreutils` is not a heavy dependency, it is pretty fragile – GNU folks regularly break something.) I will update `initool` in Macports to your latest commit.

**Comment by dbohdan** [comment]
Great! Thanks for taking care of the port.

**Comment by dbohdan** [comment]
(Oh, this is a brand new port. I didn't realize it; I thought you were updating an existing one. That's pretty cool.)

**Comment by barracuda156** [comment]
@dbohdan I made a port for `MLton` with support of PowerPC, and then started looking what I can build with it :) I saw your port in FreeBSD repo and ported over to ours.
Thank you for fixing gnuisms!

**Comment by dbohdan** [comment]
You're welcome! I see. :-) The last Mac I owned was PowerPC, a Mac Mini G4. I ran Tiger, then Leopard, then Debian on it. While I like the idea of NetBSD and OpenBSD on old hardware, it's nice that people like you keep it usable with its original operating systems.

**Comment by barracuda156** [comment]
@dbohdan I wanted to have FreeBSD as a second system for Macports, but turned out at least the current one has broken support for multicore PowerMacs: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271826
But yeah, we try to keep Darwin PPC alive and up to date as much as possible.
